/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.piano;



import java.io.*;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Haram Chae
 */
public class Piano extends javax.swing.JFrame {

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dCode = new javax.swing.JButton();
        cCode = new javax.swing.JButton();
        eCode = new javax.swing.JButton();
        fCode = new javax.swing.JButton();
        gCode = new javax.swing.JButton();
        aCode = new javax.swing.JButton();
        bCode = new javax.swing.JButton();
        c1Code = new javax.swing.JButton();
        d1Code = new javax.swing.JButton();
        e1Code = new javax.swing.JButton();
        csCode = new javax.swing.JButton();
        dsCode = new javax.swing.JButton();
        fsCode = new javax.swing.JButton();
        gsCode = new javax.swing.JButton();
        bbCode = new javax.swing.JButton();
        cs1Code = new javax.swing.JButton();
        ds1Code = new javax.swing.JButton();
        f1Code = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piano");

        dCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dCode.setText("D");
        dCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        dCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dCodeMouseClicked(evt);
            }
        });

        cCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cCode.setText("C");
        cCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        cCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cCodeMouseClicked(evt);
            }
        });

        eCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        eCode.setText("E");
        eCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        eCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        eCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eCodeMouseClicked(evt);
            }
        });

        fCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        fCode.setText("F");
        fCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        fCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fCodeMouseClicked(evt);
            }
        });

        gCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        gCode.setText("G");
        gCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        gCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gCodeMouseClicked(evt);
            }
        });

        aCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        aCode.setText("A");
        aCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        aCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aCodeMouseClicked(evt);
            }
        });

        bCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bCode.setText("B");
        bCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        bCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCodeMouseClicked(evt);
            }
        });

        c1Code.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        c1Code.setText("C1");
        c1Code.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        c1Code.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        c1Code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1CodeMouseClicked(evt);
            }
        });

        d1Code.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d1Code.setText("D1");
        d1Code.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        d1Code.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        d1Code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d1CodeMouseClicked(evt);
            }
        });

        e1Code.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        e1Code.setText("E1");
        e1Code.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        e1Code.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        e1Code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e1CodeMouseClicked(evt);
            }
        });

        csCode.setBackground(new java.awt.Color(0, 0, 0));
        csCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        csCode.setForeground(new java.awt.Color(255, 255, 255));
        csCode.setText("C#");
        csCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        csCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        csCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csCodeMouseClicked(evt);
            }
        });

        dsCode.setBackground(new java.awt.Color(0, 0, 0));
        dsCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dsCode.setForeground(new java.awt.Color(255, 255, 255));
        dsCode.setText("D#");
        dsCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        dsCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dsCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsCodeMouseClicked(evt);
            }
        });

        fsCode.setBackground(new java.awt.Color(0, 0, 0));
        fsCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        fsCode.setForeground(new java.awt.Color(255, 255, 255));
        fsCode.setText("F#");
        fsCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        fsCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fsCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fsCodeMouseClicked(evt);
            }
        });

        gsCode.setBackground(new java.awt.Color(0, 0, 0));
        gsCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        gsCode.setForeground(new java.awt.Color(255, 255, 255));
        gsCode.setText("G#");
        gsCode.setActionCommand("G#");
        gsCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        gsCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gsCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gsCodeMouseClicked(evt);
            }
        });

        bbCode.setBackground(new java.awt.Color(0, 0, 0));
        bbCode.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bbCode.setForeground(new java.awt.Color(255, 255, 255));
        bbCode.setText("Bb");
        bbCode.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        bbCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bbCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbCodeMouseClicked(evt);
            }
        });

        cs1Code.setBackground(new java.awt.Color(0, 0, 0));
        cs1Code.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cs1Code.setForeground(new java.awt.Color(255, 255, 255));
        cs1Code.setText("C#1");
        cs1Code.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        cs1Code.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cs1Code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cs1CodeMouseClicked(evt);
            }
        });

        ds1Code.setBackground(new java.awt.Color(0, 0, 0));
        ds1Code.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ds1Code.setForeground(new java.awt.Color(255, 255, 255));
        ds1Code.setText("D#1");
        ds1Code.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        ds1Code.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ds1Code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds1CodeMouseClicked(evt);
            }
        });

        f1Code.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        f1Code.setText("F1");
        f1Code.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        f1Code.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        f1Code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1CodeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(e1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(csCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(fsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bbCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(cs1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ds1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cs1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCode, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCodeMouseClicked
// TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\C.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_cCodeMouseClicked

    private void dCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\D.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_dCodeMouseClicked

    private void eCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\E.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_eCodeMouseClicked

    private void fCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\F.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_fCodeMouseClicked

    private void gCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\G.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_gCodeMouseClicked

    private void aCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\A.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_aCodeMouseClicked

    private void bCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\B.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_bCodeMouseClicked

    private void c1CodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1CodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\C1.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_c1CodeMouseClicked

    private void d1CodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1CodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\D1.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_d1CodeMouseClicked

    private void e1CodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1CodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\E1.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_e1CodeMouseClicked

    private void f1CodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1CodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\F1.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_f1CodeMouseClicked

    private void csCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\C_s.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_csCodeMouseClicked

    private void dsCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\D_s.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_dsCodeMouseClicked

    private void fsCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fsCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\F_s.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_fsCodeMouseClicked

    private void gsCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gsCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\G_s.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_gsCodeMouseClicked

    private void bbCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbCodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\Bb.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_bbCodeMouseClicked

    private void cs1CodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cs1CodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\C_s1.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_cs1CodeMouseClicked

    private void ds1CodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds1CodeMouseClicked
        // TODO add your handling code here:
    try{
        File audio = new File("D:\\Music_Note\\Music_Note\\D_s1.wav");
        AudioInputStream music = AudioSystem.getAudioInputStream(audio);
        Clip clip = AudioSystem.getClip();
        clip.open(music);
        clip.start();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_ds1CodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aCode;
    private javax.swing.JButton bCode;
    private javax.swing.JButton bbCode;
    private javax.swing.JButton c1Code;
    private javax.swing.JButton cCode;
    private javax.swing.JButton cs1Code;
    private javax.swing.JButton csCode;
    private javax.swing.JButton d1Code;
    private javax.swing.JButton dCode;
    private javax.swing.JButton ds1Code;
    private javax.swing.JButton dsCode;
    private javax.swing.JButton e1Code;
    private javax.swing.JButton eCode;
    private javax.swing.JButton f1Code;
    private javax.swing.JButton fCode;
    private javax.swing.JButton fsCode;
    private javax.swing.JButton gCode;
    private javax.swing.JButton gsCode;
    // End of variables declaration//GEN-END:variables
}
